aliyun:
  url: http://106.14.83.136
spring:
  application.name: experimentSpb
  profiles.active: test
  cloud:
    nacos:
      discovery:
        server-addr: ${aliyun.url}:8848
    sentinel:
      transport:
        port: 8719
        dashboard: 106.14.83.136:8080
server:
  port: 8080
#  servlet.context-path: /${spring.application.name}
app.id: ${spring.application.name}
apollo.meta: ${aliyun.url}:8280